version: '3'

services:
    nginx:
        image: nginx
        ports:
            - '8080:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'

    tserver1:
        image: eogns47/nsfserver:v1
        ports:
            - '8082:8080'
        container_name: tserver1

    tserver2:
        image: eogns47/nsfserver:v1
        ports:
            - '8081:8080'
        container_name: tserver2
