version: '3'

services:
    nginx:
        image: eogns47/mynginx
        ports:
            - '9090:80'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        container_name: nginx
        volumes:
            - nginx:/logs

    tserver1:
        image: eogns47/nsfserver:v1
        ports:
            - '8082:8080'
        container_name: tserver1
        environment:
            - ENV=blue
        volumes:
            - nsf_log:/logs

    tserver2:
        image: eogns47/nsfserver:v1
        ports:
            - '8081:8080'
        container_name: tserver2
        environment:
            - ENV=blue
        volumes:
            - nsf_log:/logs
volumes:
    nginx:
        driver: local

    nsf_log:
        driver: local
